# Generated by Django 4.1.3 on 2022-11-06 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='announcementtype',
            name='type',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Le texte doit être en majuscule.')]),
        ),
    ]
